application: encuentra-casa
version: 5
runtime: python27
api_version: 1
threadsafe: yes

handlers:

#Visor de pensiones
- url: /verPension
  script: verPension.application

#Visores para administrador
- url: /estadisticas
  script: estadisticas.application

- url: /adminLogin
  script: adminLogin.application

- url: /adminIndex
  script: adminIndex.application

- url: /publicarNuevo
  script: publicarNuevo.application

- url: /registrarNuevaPension
  script: registrarNuevaPension.application

- url: /editarPension
  script: editarPension.application

- url: /actualizarPension
  script: actualizarPension.application

#Comportamientos admin
- url: /validar_inicio_sesion
  script: validar_inicio_sesion.application

- url: /crearSesion
  script: crearSesion.application

- url: /cerrarSesion
  script: cerrarSesion.application

- url: /cargarArchivo
  script: cargarArchivo.application

- url: /mostrar
  script: mostrar.application

- url: /eliminarFoto
  script: eliminarFoto.application

- url: /registrarUsuario
  script: registrarUsuario.application



#Carpetas internas.
- url: /view
  script: viewhandler.application

- url: /img
  static_dir: img

- url: /css
  static_dir: admin/css

- url: /fonts
  static_dir: admin/fonts

- url: /js
  static_dir: admin/js

#index.html && main.py
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest